version: '3.1'

services:

  db:
    container_name: zuliandb
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB=zulian
    ports:
      - 5432:5432
    #volumes:
      #- ./dbInit/init.sql:/docker-entrypoint-initdb.d/init.sql