mp:
  jwt:
    verify:
      # Parameters here must match in GeneratToken service else the token is not valid
      issuer: https://zg-api # Becarefull if you change this value, the JWT are not valid anymore if the issuer at generate is not same
      aud: zg-api
      publickey:
        location: META-INF/resources/publicKey.pem
quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      max-size: 16
      min-size: 4
      url: jdbc:postgresql://localhost:5432/zulian
    password: root
    username: root
  hibernate-orm:
    database:
      generation: update
  http:
    port: 5200
smallrye:
  jwt:
    sign:
      key-location: META-INF/resources/privateKey.pem



